# Generated by Django 3.0.6 on 2020-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200519_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
