# Generated by Django 3.0.6 on 2020-05-19 18:56

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ManyToManyField(null=True, related_name='from_account', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ManyToManyField(null=True, related_name='to_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
