# Generated by Django 3.0.6 on 2020-05-19 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ManyToManyField(related_name='transactions_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ManyToManyField(related_name='transactions_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
