# Generated by Django 3.0.6 on 2020-05-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20200519_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='SGD', max_length=5),
        ),
    ]
