# Generated by Django 3.0.6 on 2020-05-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_converted_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
