apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: cG9zdGdyZXMtdXNlci0yVnM4RQ== # postgres-user-2Vs8E
  password: TTNKLjxqPmslJyNRYnVUWSJzdzR7ej08dCZnanptNHBlVVk8 # M3J.<j>k%'#QbuTY"sw4{z=<t&gjzm4peUY<